# use an official image of node.js runtime
FROM node:22-alpine

# set the working directory inside the container
WORKDIR /app

# copy all package.json files in the working directory
COPY package*.json ./

# install dependencies
RUN npm install

COPY . .

ENV PORT=3000

CMD ["node","index.js"]